"""initial_escrow_tables

Revision ID: 3f6b763892a7
Revises: 
Create Date: 2026-04-18 13:49:48.284248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f6b763892a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('role', sa.Enum('VENDOR', 'BUYER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('bvn', sa.String(length=11), nullable=True),
    sa.Column('wallet_balance', sa.Numeric(precision=20, scale=0), nullable=False),
    sa.Column('escrow_balance', sa.Numeric(precision=20, scale=0), nullable=False),
    sa.Column('paystack_recipient_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('devices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('device_fingerprint_hash', sa.String(length=255), nullable=False),
    sa.Column('is_trusted', sa.Boolean(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_fingerprint_hash'), 'devices', ['device_fingerprint_hash'], unique=True)
    op.create_table('payment_methods',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('paystack_auth_code', sa.String(length=200), nullable=False),
    sa.Column('card_last4', sa.String(length=4), nullable=False),
    sa.Column('card_brand', sa.String(length=20), nullable=False),
    sa.Column('issuing_vendor_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuing_vendor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_methods_user_id'), 'payment_methods', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('tap_fee', sa.Integer(), nullable=False),
    sa.Column('vendor_net', sa.Integer(), nullable=False),
    sa.Column('first_disbursement', sa.Integer(), nullable=False),
    sa.Column('second_disbursement', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID_50', 'DELIVERED', 'SETTLED', 'DISPUTED', 'REFUNDED', 'EXPIRED', name='txstatus'), nullable=False),
    sa.Column('paystack_reference', sa.String(length=100), nullable=False),
    sa.Column('paystack_transfer_ref_1', sa.String(length=100), nullable=True),
    sa.Column('paystack_transfer_ref_2', sa.String(length=100), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('link_slug', sa.String(length=100), nullable=False),
    sa.Column('is_one_tap', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_link_slug'), 'transactions', ['link_slug'], unique=True)
    op.create_index(op.f('ix_transactions_paystack_reference'), 'transactions', ['paystack_reference'], unique=True)
    op.create_index(op.f('ix_transactions_vendor_id'), 'transactions', ['vendor_id'], unique=False)
    op.create_table('platform_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('total_volume', sa.Integer(), nullable=False),
    sa.Column('paystack_fee', sa.Integer(), nullable=False),
    sa.Column('tap_gross_profit', sa.Integer(), nullable=False),
    sa.Column('tap_net_profit', sa.Integer(), nullable=False),
    sa.Column('sweep_status', sa.Enum('PENDING', 'SWEPT', name='sweepstatus'), nullable=False),
    sa.Column('swept_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sweep_transfer_ref', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_ledger')
    op.drop_index(op.f('ix_transactions_vendor_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_paystack_reference'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_link_slug'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_payment_methods_user_id'), table_name='payment_methods')
    op.drop_table('payment_methods')
    op.drop_index(op.f('ix_devices_device_fingerprint_hash'), table_name='devices')
    op.drop_table('devices')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
